apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: magradze/testrepo:producer
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"

